LLM_PJ/urls.py
from django.contrib import admin
from django.urls import path, include
from products import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.index, name="index"),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("products/", include("products.urls")),
    path("users/", include("users.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
]

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path("<int:pk>/", views.product_detail, name="product_detail"),
    path("create/", views.create, name="create"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/like/", views.like, name="like"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("profile/<str:username>/", views.profile, name="profile"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser

class Users(AbstractUser):
    pass

products/models.py
from django.db import models
from django.conf import settings


class Product(models.Model):
    flavor = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to="flavor/", blank=True, default="default/default_product.png")
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_products"
    )

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import (
    UserCreationForm, 
    UserChangeForm,
)
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):  
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ()


class CustomUserChangeForm(UserChangeForm):
    password = None
    class Meta:
        model = get_user_model()
        fields = [
            "first_name",
            "last_name",
            "email",
        ]

products/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        exclude = ("like_users",)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
)
from django.contrib.auth import (
    login as auth_login,
    logout as auth_logout,
    update_session_auth_hash,
)
from django.views.decorators.http import (
    require_POST,
    require_http_methods,
)
from .forms import (
    CustomUserCreationForm,
    CustomUserChangeForm,
)


@require_http_methods(["GET", "POST"])
def signup(request):
    if request.method=='POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("index")
    else:
        form = CustomUserCreationForm()
    context = {"form": form}
    return render(request, "accounts/signup.html", context)


@require_http_methods(["GET", "POST"])
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            next_url = request.GET.get("next") or "index"
            return redirect(next_url)
    else:
        form = AuthenticationForm()

    context = {"form": form}
    return render(request, "accounts/login.html", context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect("index")


@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    return redirect("index")


@require_http_methods(["GET", "POST"])
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("index")
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {"form": form}
    return render(request, "accounts/update.html", context)


def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("index")
    else:
        form = PasswordChangeForm(request.user)
    context = {"form": form}
    return render(request, "accounts/change_password.html", context)

products/views.py
from django.shortcuts import (
    render, 
    redirect,
    get_object_or_404,
)
from django.views.decorators.http import (
    require_http_methods, 
    require_POST,
)
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ProductForm
from .models import Product


def index(request):
    products = Product.objects.all().order_by("-pk")
    context = {
        "products": products,
    }
    return render(request, "products/index.html", context)


def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        "product": product,
    }
    return render(request, "products/product_detail.html", context)


@login_required
def create(request):
    if request.user.is_staff:
        if request.method == "POST":
            form = ProductForm(request.POST, request.FILES)
            if form.is_valid():
                product = form.save(commit=False)
                product.save()
                return redirect("index")
        else:
            form = ProductForm()
        context = {"form": form}
        return render(request, "products/create.html", context)
    messages.error(request, "접근이 불가합니다.")
    return redirect("index")


@require_POST
def delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.user.is_staff:
        product = get_object_or_404(Product, pk=pk)
        product.delete()
        return redirect("index")
    messages.error(request, "접근이 불가합니다.")
    return redirect("index")


@login_required
@require_http_methods(["GET", "POST"])
def update(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.user.is_staff:
        if request.method == "POST":
            form = ProductForm(request.POST, request.FILES, instance=product)
            if form.is_valid():
                product = form.save()
                return redirect("products:product_detail", product.pk)
        else:
            form = ProductForm(instance=product)
    else:
        messages.error(request, "접근이 불가합니다.")
        return redirect("index")
    
    context = {
        "form": form,
        "product": product,
    }
    return render(request, "products/update.html", context)


@require_POST
def like(request, pk):
    if request.user.is_authenticated:
        product = get_object_or_404(Product, pk=pk)
        if product.like_users.filter(pk=request.user.pk).exists():
            product.like_users.remove(request.user)
        else:
            product.like_users.add(request.user)
        return redirect("products:product_detail", pk)
    return redirect("products:login")

users/views.py
from django.shortcuts import (
    render, 
    get_object_or_404,
)
from django.contrib.auth import get_user_model

def profile(request, username):
    member = get_object_or_404(get_user_model(), username=username)
    context = {
        "member": member,
    }
    return render(request, "users/profile.html", context)

accounts/templates/accounts/change_password.html
{% extends "base.html" %}

{% block content %}
<h1>change_password</h1>
<form action="{% url 'accounts:change_password' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">수정</button>
</form>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<h1>Login</h1>
<form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">로그인</button>
</form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
<h1>Signup</h1>
<form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">가입하기</button>
</form>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends "base.html" %}

{% block content %}
<h1>회원 수정</h1>
<form action="{% url 'accounts:update' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">수정</button>
</form>
<a href="{% url 'accounts:change_password' %}"><button>비밀번호 변경하러 가기</button></a>
{% endblock content %}

products/templates/products/create.html
{% extends "base.html" %}

{% block content %}
    <h2>제품등록</h2>
    <form action="{% url 'products:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">저장</button>
    </form>
{% endblock content %}

products/templates/products/index.html
{% extends "base.html" %}

{% block content %}
    <h1>index</h1>
    {% for product in products %}
        <a href="{% url 'products:product_detail' product.pk %}">
            <p>[ {{ product.pk }} ] {{ product.flavor }}</p>
        </a>
    {% endfor %}
{% endblock content %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <style>
        .image-size {
            width: 400px;
            height: 400px;
        }
    </style>
    
    <h1>상품상세</h1>
    <p>{{ product.flavor }}</p>

    {% if product.image %}
        <img src="{{ product.image.url }}" class="image-size">
    {% endif %}

    <p>설명: {{ product.content }}</p>
    <p>작성일시: {{ product.created_at }}</p>
    <p>수정일시: {{ product.updated_at }}</p>

    <a href="{% url 'products:update' product.pk %}">
        <button>수정하기</button>
    </a>

    <form action="{% url 'products:delete' product.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="삭제">
    </form>
    {% if user.is_staff %}
    {% endif %}
    
    <form action="{% url 'products:like' product.pk %}" method="POST">
        {% csrf_token %}
        {% if request.user in product.like_users.all %}
            <input type="submit" value="좋아요 취소하기">
        {% else %}
            <input type="submit" value="좋아요하기">
        {% endif %}
    </form>
{% endblock content %}

products/templates/products/update.html
{% extends "base.html" %}

{% block content %}
    <h1>상품수정</h1>
    <form action="{% url 'products:update' product.pk %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">수정</button>
    </form>
    
    <a href="{% url 'products:product_detail' product.pk %}">이전으로</a>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sparta Icecream</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body style="background-color: rgb(253 248 231) !important;">
    <nav class="navbar bg-body-tertiary align-text-middle" style="background-color: rgb(253 248 231) !important;">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">
            <img src="{% static 'image/LOGO.png' %}" alt="Logo" width="50" height="50" class="d-inline-block align-text-middle">
            Sparta Icecream
          </a>
          <div class="">
            {% if user.is_staff %}
              <a href="{% url 'products:create' %}"><button type="button">상품 추가</button></a>
            {% endif %}

            {% if request.user.is_authenticated %}
              <div class="btn-group">
                <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  메뉴
                </button>
                <ul class="dropdown-menu dropdown-menu-lg-end">
                  <li><a class="dropdown-item" href="{% url 'users:profile' request.user.username %}">프로필</a></li>
                  <li><a class="dropdown-item" href="{% url 'accounts:update' %}">회원정보수정</a></li>
                  <li>
                    <form action="{% url 'accounts:logout' %}" method="POST">
                      {% csrf_token %}
                      <button class="dropdown-item" type="submit">로그아웃</button>
                    </form>
                  </li>
                  <li><hr class="dropdown-divider"></li>
                  <li>
                    <form action="{% url 'accounts:delete' %}" method="POST">
                      {% csrf_token %}
                      <button class="dropdown-item">회원탈퇴</button>
                    </form>
                  </li>
                </ul>
              </div>
            {% else %}
              <a href="{% url 'accounts:signup' %}"><button type="button">가입</button></a>
              <a href="{% url 'accounts:login' %}"><button type="button">로그인</button></a>
            {% endif %}
          </div>
        </div>
    </nav>

    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    
    <div class="footer">

    </div>
    {% if messages %}
    <script>
        var displayedMessages = [];
        {% for message in messages %}
            if (!displayedMessages.includes("{{ message }}")) {
                alert("{{ message }}");
                displayedMessages.push("{{ message }}");
            }
        {% endfor %}
    </script>
    {% endif %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1>프로필</h1>

    username : {{ member.username }} <br>
    date_joined : {{ member.date_joined }} <br>
    <br>

    <a href="{% url 'accounts:update' %}"><button>회원정보 수정</button></a>
    <a href="{% url 'accounts:change_password' %}"><button>비밀번호 변경</button></a> <br>
    <br>

    {% if request.user == member %}
        내가 찜한 맛
        {% for product in member.like_products.all %}
            <ul>
                <a href="{% url 'products:product_detail' product.pk %}">{{ product.flavor }}</a>
            </ul>
        {% endfor %}
    {% endif %}
{% endblock content %}